states = [
    {"state": ["capitol", "bird", "flower"]},
    {"alabama": ["montgomery", "yellowhammer", "camellia"]},
    {"alaska": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"arizona": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"arkansas": ["little rock", "northern mockingbird", "apple blossom"]},
    {"california": ["capitol", "bird", "flower"]},
    {"colorado": ["montgomery", "yellowhammer", "camellia"]},
    {"connecticut": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"delaware": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"florida": ["little rock", "northern mockingbird", "apple blossom"]},
    {"georgia": ["capitol", "bird", "flower"]},
    {"hawaii": ["montgomery", "yellowhammer", "camellia"]},
    {"idaho": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"illinois": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"indiana": ["little rock", "northern mockingbird", "apple blossom"]},
    {"iowa": ["capitol", "bird", "flower"]},
    {"kansas": ["montgomery", "yellowhammer", "camellia"]},
    {"kentucky": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"louisiana": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"maine": ["little rock", "northern mockingbird", "apple blossom"]},
    {"maryland": ["capitol", "bird", "flower"]},
    {"massachusetts": ["montgomery", "yellowhammer", "camellia"]},
    {"michigan": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"minnesota": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"mississippi": ["little rock", "northern mockingbird", "apple blossom"]},
    {"missouri": ["capitol", "bird", "flower"]},
    {"montana": ["montgomery", "yellowhammer", "camellia"]},
    {"nebraska": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"nevada": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"new hampshire": ["little rock", "northern mockingbird", "apple blossom"]},
    {"new jersey": ["capitol", "bird", "flower"]},
    {"new mexico": ["montgomery", "yellowhammer", "camellia"]},
    {"new york": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"north carolina": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"north dakota": ["little rock", "northern mockingbird", "apple blossom"]},
    {"ohio": ["capitol", "bird", "flower"]},
    {"oklahoma": ["montgomery", "yellowhammer", "camellia"]},
    {"oregon": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"pennsylvania": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"rhode island": ["little rock", "northern mockingbird", "apple blossom"]},
    {"south carolina": ["capitol", "bird", "flower"]},
    {"south dakota": ["montgomery", "yellowhammer", "camellia"]},
    {"tennessee": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"texas": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"utah": ["little rock", "northern mockingbird", "apple blossom"]},
    {"vermont": ["capitol", "bird", "flower"]},
    {"virginia": ["montgomery", "yellowhammer", "camellia"]},
    {"washington": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"west virginia": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"wisconsin": ["little rock", "northern mockingbird", "apple blossom"]},
    {"wyoming": ["little rock", "northern mockingbird", "apple blossom"]}
]
