dir_backup = {
    "states": [
        {"state": ["capitol", "bird", "flower"]},
        {"alabama": ["montgomery", "yellowhammer", "camellia"]},
        {"alaska": ["juneau", "willow ptarmigan", "forget-me-not"]},
        {"arizona": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
        {"arkansas": ["little rock", "northern mockingbird", "apple blossom"]},
        {"california": ["sacramento", "california quail", "california poppy"]},
        {"colorado": ["denver", "lark bunting", "rocky mountain columbine"]},
        {"connecticut": ["hartford", "american robin", "mountain laurel"]},
        {"delaware": ["dover", "delaware blue hen", "peach blossom"]},
        {"florida": ["tallahassee", "northern mockingbird", "orange blossom"]},
        {"georgia": ["atlanta", "brown thrasher", "cherokee rose"]},
        {"hawaii": ["honolulu", "hawaiian goose", "hawaiian hibiscus"]},
        {"idaho": ["boise", "mountain bluebird", "syringa (mock orange)"]},
        {"illinois": ["springfield", "northern cardinal", "violet"]},
        {"indiana": ["indianapolis", "northern cardinal", "peony"]},
        {"iowa": ["des moines", "eastern goldfinch", "wild prairie rose"]},
        {"kansas": ["topeka", "western meadowlark", "sunflower"]},
        {"kentucky": ["frankfort", "northern cardinal", "goldenrod"]},
        {"louisiana": ["baton rouge", "brown pelican", "magnolia"]},
        {"maine": ["augusta", "chickadee", "white pine cone and tassel"]},
        {"maryland": ["annapolis", "baltimore oriole", "black-eyed susan"]},
        {"massachusetts": ["boston", "black-capped chickadee", "mayflower"]},
        {"michigan": ["lansing", "american robin", "apple blossom"]},
        {"minnesota": ["saint paul", "common loon", "pink and white lady slipper"]},
        {"mississippi": ["jackson", "northern mockingbird", "magnolia"]},
        {"missouri": ["jefferson", "eastern bluebird", "hawthorn"]},
        {"montana": ["helena", "western meadowlark", "bitter root"]},
        {"nebraska": ["lincoln", "western meadowlark", "goldenrod"]},
        {"nevada": ["carson city", "mountain bluebird", "sagebrush"]},
        {"new hampshire": ["concord", "purple finch", "purple lilac"]},
        {"new jersey": ["trenton", "eastern goldfinch", "violet"]},
        {"new mexico": ["santa fe", "roadrunner", "yucca flower"]},
        {"new york": ["albany", "eastern bluebird", "rose"]},
        {"north carolina": ["raleigh", "northern cardinal", "flowering dogwood"]},
        {"north dakota": ["bismarck", "western meadowlark", "wild prairie rose"]},
        {"ohio": ["columbus", "northern cardinal", "scarlet carnation"]},
        {"oklahoma": ["oklahoma city", "scissor-tailed flycatcher", "oklahoma rose"]},
        {"oregon": ["salem", "western meadowlark", "oregon grape"]},
        {"pennsylvania": ["harrisburg", "ruffed grouse", "mountain laurel"]},
        {"rhode island": ["providence", "rhode island red", "violet"]},
        {"south carolina": ["columbia", "carolina wren", "yellow jessamine"]},
        {"south dakota": ["pierre", "ring-necked pheasant", "pasque flower"]},
        {"tennessee": ["nashville", "northern mockingbird", "iris"]},
        {"texas": ["austin", "northern mockingbird", "bluebonnet"]},
        {"utah": ["salt lake city", "california gull", "sego lilly"]},
        {"vermont": ["montpelier", "hermit thrush", "red clover"]},
        {"virginia": ["richmond", "northern cardinal", "american dogwood"]},
        {"washington": ["olympia", "willow goldfinch", "coast rhododendron"]},
        {"west virginia": ["charleston", "northern cardinal", "rhododendron"]},
        {"wisconsin": ["madison", "american robin", "wood violet"]},
        {"wyoming": ["cheyenne", "western meadowlark", "indian paintbrush"]}
    ]
}
