states = [
    {"state": ["capitol", "bird", "flower"]},
    {"alabama": ["montgomery", "yellowhammer", "camellia"]},
    {"alaska": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"arizona": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"arkansas": ["little rock", "northern mockingbird", "apple blossom"]},
    {"california": ["capitol", "california quail", "california poppy"]},
    {"colorado": ["montgomery", "lark bunting", "rocky mountain columbine"]},
    {"connecticut": ["juneau", "american robin", "mountain laurel"]},
    {"delaware": ["phoenix", "delaware blue hen", "peach blossom"]},
    {"florida": ["little rock", "northern mockingbird", "orange blossom"]},
    {"georgia": ["capitol", "brown thrasher", "cherokee rose"]},
    {"hawaii": ["montgomery", "hawaiian goose", "hawaiian hibiscus"]},
    {"idaho": ["juneau", "mountain bluebird", "syringa (mock orange)"]},
    {"illinois": ["phoenix", "northern cardinal", "violet"]},
    {"indiana": ["little rock", "northern cardinal", "peony"]},
    {"iowa": ["capitol", "eastern goldfinch", "wild prairie rose"]},
    {"kansas": ["montgomery", "yellowhammer", "camellia"]},
    {"kentucky": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"louisiana": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"maine": ["little rock", "northern mockingbird", "apple blossom"]},
    {"maryland": ["capitol", "bird", "flower"]},
    {"massachusetts": ["montgomery", "yellowhammer", "camellia"]},
    {"michigan": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"minnesota": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"mississippi": ["little rock", "northern mockingbird", "apple blossom"]},
    {"missouri": ["capitol", "bird", "flower"]},
    {"montana": ["montgomery", "yellowhammer", "camellia"]},
    {"nebraska": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"nevada": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"new hampshire": ["little rock", "northern mockingbird", "apple blossom"]},
    {"new jersey": ["capitol", "bird", "flower"]},
    {"new mexico": ["montgomery", "yellowhammer", "camellia"]},
    {"new york": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"north carolina": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"north dakota": ["little rock", "northern mockingbird", "apple blossom"]},
    {"ohio": ["capitol", "bird", "flower"]},
    {"oklahoma": ["montgomery", "yellowhammer", "camellia"]},
    {"oregon": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"pennsylvania": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"rhode island": ["little rock", "northern mockingbird", "apple blossom"]},
    {"south carolina": ["capitol", "bird", "flower"]},
    {"south dakota": ["montgomery", "yellowhammer", "camellia"]},
    {"tennessee": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"texas": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"utah": ["little rock", "northern mockingbird", "apple blossom"]},
    {"vermont": ["capitol", "bird", "flower"]},
    {"virginia": ["montgomery", "yellowhammer", "camellia"]},
    {"washington": ["juneau", "willow ptarmigan", "forget-me-not"]},
    {"west virginia": ["phoenix", "cactus wren", "saguaro cactus blossom"]},
    {"wisconsin": ["little rock", "northern mockingbird", "apple blossom"]},
    {"wyoming": ["little rock", "northern mockingbird", "apple blossom"]}
]
